In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
array=np.array(60)
print(array)
print(array.dtype)

60
int64


In [ ]:
one=np.array([1,2,3,4,5,6,7,8,9,10])
print(one)
print(one[6])
print(one[2:5])
print(one[:8])
print(one[2:])

[ 1  2  3  4  5  6  7  8  9 10]
7
[3 4 5]
[1 2 3 4 5 6 7 8]
[ 3  4  5  6  7  8  9 10]


In [ ]:
two=np.array([[2,3,4,5],[6,7,8,9]])
print(two)
print(two[1,1])
print(two[0,1:])
print(two[1,:3])

[[2 3 4 5]
 [6 7 8 9]]
7
[3 4 5]
[6 7 8]


In [ ]:
three=np.array([[[2,1,3,4,5],[3,5,7,9,1]],[[3,5,8,1,0],[2,6,7,8,0]]])
print(three)
print(three[1,0,2:])
print(three[0,1,0:4])
print(three[0,0,1:4])

[[[2 1 3 4 5]
  [3 5 7 9 1]]

 [[3 5 8 1 0]
  [2 6 7 8 0]]]
[8 1 0]
[3 5 7 9]
[1 3 4]


In [ ]:
arr=np.array(45.0,dtype='i')
print(arr)
print(arr.dtype)

45
int32


In [ ]:
arr=np.array(56,dtype='float')
print(arr)
print(arr.dtype)

56.0
float64


In [ ]:
one=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(one)
print(one.shape)
two_D=one.reshape(4,4)
print(two_D)
print(two_D.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)


In [ ]:
one=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(one)
print(one.shape)
three_D=one.reshape(2,2,4)
print(three_D)
print(three_D.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
(2, 2, 4)


In [ ]:
one=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(one)
print(one.shape)
multi_D=one.reshape(2,2,2,2)
print(multi_D)
print(multi_D.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
(2, 2, 2, 2)
